language: python
sudo: true
python: 3.6

cache:
  directories:
    - $HOME/.cache/pip
services:
  - mysql
  - postgresql
addons:
  postgresql: "9.4"

# We spell out the text matrix tox generates explicitly here to get the most use out of both.
matrix:
  include:
    - env: TOXENV=tests-sqlite-codecov
    - env: TOXENV=tests-mysql
    - env: TOXENV=tests-postgres
    - env: TOXENV=installation
    - env: TOXENV=lint
    - env: TOXENV=docs

install:
  - ./.travis/install.sh

script:
  - cd src && tox
