language: python
sudo: false
python: 3.6
dist: trusty
install:
  - pip install -U pip setuptools wheel typing codecov coverage
  - pip install -Ur src/requirements/dev.txt -r src/requirements/fancy.txt
  - pip install -Ur src/requirements.txt
script:
  - cd src/
  - python manage.py collectstatic --noinput
  - python manage.py compress
  - python manage.py compilemessages
  - pylama
  - isort -rc -c .
  - py.test -p no:sugar --cov=pretalx tests/ && codecov  # Until https://github.com/Frozenball/pytest-sugar/pull/133 or similar is merged
  - pip list -o --format=columns
