version: 2
updates:
  # Configuration for npm
  # - package-ecosystem: npm
  #   directory: "/webapp"
  #   schedule:
  #     interval: daily
  #   open-pull-requests-limit: 10
  #   dependency-type: production  # don't update dev dependencies â€“ do we want that?
  #   ignore:
  #   - dependency-name: "@babel*"
  #   - dependency-name: "@vue*"
  #   - dependency-name: "@eslint*"
  - package-ecosystem: pip
    directory: "/server"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
